language: node_js
node_js:
  - 12

jobs:
  include:
    # - script: npm run lint
    # - script: npm run test
    - script: ./cron.sh --t262-github-remote "https://$GITHUB_TOKEN@github.com/test262-automation/test262.git"
      # if: type IN (cron) AND branch = master
    # - script: ./cron.sh --t262-github-remote "https://test262-automation:$GITHUB_TOKEN@github.com/test262-automation/test262.git" --debug
      # if: type IN (cron) AND NOT branch = master

